# Audio and system configuration shared by edge and server

audio_sample_rate: 48000
audio_channels: 1
audio_bit_depth: 16
audio_backend: alsa
darkice_quality: 0.4      # VBR quality (0.1 to 1.0)
darkice_bitrate: 32       # Fallback bitrate if VBR is not used

# Audio processing default values
audio_processing:
  compress_ratio: 3.0
  compress_threshold: -12.0
  attack_time: 0.1
  release_time: 0.5
  highpass_freq: 80.0
  lowpass_freq: 8000.0
  delay_time: 0.0
  delay_feedback: 0.0
  gate_threshold: -40.0
  normalize_target: -14.0
# mpv_audio_device: "pulse/alsa_output.platform-soc_sound.stereo-fallback"
mpv_audio_device: "alsa/tee_output"
mpv_audio_device_alsa: "alsa/tee_output"
mpv_audio_format: "s16"
mpv_audio_buffer_secs: 10  # Audio buffer size in seconds for mpv player
mpv_cache_secs: 60
mpv_demuxer_max_bytes: "20M"
# PulseAudio optimizations for preventing underruns
pulse_latency_msec: 100  # Higher latency for stability
pulse_fragment_size: 1024  # Smaller fragments for better control 