# Development placeholder - actual files generated by Ansible from templates
# This file exists only to eliminate import warnings in development environment
# The real audio_manager.py is generated from templates/audio_manager.py.j2

class AudioManager:
    """Development placeholder for AudioManager class."""
    def __init__(self, *args, **kwargs):
        pass
