---
- name: Update Pi Agent Files Only
  hosts: sculptures
  become: yes
  vars:
    sculpture_dir: /opt/sculpture-system
  vars_files:
    - ../../audio_config.yml
    - ../../playlists.yml

  tasks:
    - name: Update pi-agent.py
      template:
        src: "../pi-agent/pi-agent.py.j2"
        dest: "{{ sculpture_dir }}/pi-agent.py"
        mode: '0755'
      notify: Restart pi-agent

    - name: Update mqtt_client.py
      template:
        src: "../pi-agent/mqtt_client.py.j2"
        dest: "{{ sculpture_dir }}/mqtt_client.py"
        mode: '0644'
      notify: Restart pi-agent

    - name: Update playlist_manager.py
      template:
        src: "../pi-agent/playlist_manager.py.j2"
        dest: "{{ sculpture_dir }}/playlist_manager.py"
        mode: '0644'
      notify: Restart pi-agent

  handlers:
    - name: Restart pi-agent
      systemd:
        name: pi-agent
        state: restarted 