---
- name: SSH Key Deployment & Access Management
  hosts: sculptures
  become: yes
  vars:
    sculpture_dir: /opt/sculpture-system
  vars_files:
    - ../../audio_config.yml
    - ../../playlists.yml

  tasks:
    # SSH Key Deployment for Server-Agent Access
    - name: Copy server's SSH public key locally
      local_action:
        module: ansible.builtin.command
        cmd: sudo cat /home/unix/.ssh/id_rsa.pub
      register: unix_ssh_key_local
      run_once: true
      become: no
      tags: [ssh_keys]

    - name: Ensure pi user .ssh directory exists
      file:
        path: /home/pi/.ssh
        state: directory
        owner: pi
        group: pi
        mode: '0700'
      tags: [ssh_setup]

    - name: Deploy server's SSH key to pi user
      authorized_key:
        user: pi
        key: "{{ unix_ssh_key_local.stdout }}"
        comment: "server-agent access key"
        state: present
      tags: [ssh_keys] 